# IQOS Social Intelligence Analysis Configuration

# Data Settings
data:
  input_file: "data/input/dataset_instagram-scraper_2025-10-21_12-40-20-239.json"
  output_dir: "output/reports"
  image_cache_dir: "data/images"
  processed_state_dir: "data/processed"

# Processing Mode
processing:
  mode: "sample"  # "sample" or "full"
  sample_size: 50
  
# LM Studio Settings
llm:
  api_endpoint: "http://127.0.0.1:512/v1"  # Your actual endpoint
  model_name: "google/gemma-3-12b"
  timeout: 120
  max_retries: 3
  temperature: 0.3

# Image Settings
images:
  download_enabled: true
  max_images_per_post: 10
  
# Comment Settings
comments:
  max_comments: 20
  
# Progress
progress:
  save_interval: 10
  log_level: "INFO"